name: MSYS2

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]

jobs:
  msys2-mingw64:
    runs-on: windows-2025
    steps:
      - name: Gather Facts
        id: facts
        run : |
          Get-PSDrive -PSProvider FileSystem | Format-Table -AutoSize -Wrap
          Get-CIMInstance -Class Win32_Processor | Select-Object -Property Name
          $BUILD_DRIVE = Split-Path $env:GITHUB_WORKSPACE -Qualifier
          echo "drive=$BUILD_DRIVE" >> $env:GITHUB_OUTPUT

      - name: Setup JIT minidump
        if: ${{ matrix.msystem != 'CLANGARM64' }}
        run: |
          Set-Location '${{ runner.temp }}'
          Invoke-WebRequest -Uri 'https://download.sysinternals.com/files/Procdump.zip' -OutFile Procdump.zip
          Expand-Archive Procdump.zip -DestinationPath .
          New-Item -Path '_dumps' -ItemType Directory
          .\procdump64.exe -accepteula -ma -i "${{ runner.temp }}/_dumps"
          .\procdump.exe -accepteula -ma -i "${{ runner.temp }}/_dumps"

      - name: Configure Pagefile
        if: ${{ matrix.msystem != 'CLANGARM64' }}
        # https://github.com/al-cheb/configure-pagefile-action/issues/16
        continue-on-error: true
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 4GB
          maximum-size: 16GB
          # Needs to be C:, see https://github.com/al-cheb/configure-pagefile-action/issues/18
          disk-root: "C:"

      - uses: actions/checkout@v4
        with:
          path: temp
          fetch-depth: 0
          filter: blob:none
          persist-credentials: false

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git python base-devel mingw-w64-x86_64-gcc
          release: ${{ runner.arch != 'ARM64' }}
          location: '${{ steps.facts.outputs.drive }}\M'

      - name: Move Checkout
        run: |
          $path = "${{ steps.facts.outputs.drive }}\_"
          If (Test-Path "$path") { rm -r -fo "$path" }
          Move-Item -Path ".\temp" -Destination "$path"

      - name: CI-Build
        shell: msys2 {0}
        id: build
        run: |
          echo 'Running in MSYS2!'
          cd "$(cygpath '${{ steps.facts.outputs.drive }}/_')"
          MINGW_ARCH=MINGW64 ./.ci/ci-build.sh

      - name: "Upload binaries"
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.msystem }}-packages
          path: ${{ steps.facts.outputs.drive }}/_/artifacts/*.pkg.tar.*
          if-no-files-found: ignore

      - name: "Upload dumps"
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.msystem }}-dumps
          path: ${{ runner.temp }}/_dumps/*.dmp
          if-no-files-found: ignore

      - name: "Clean up runner"
        if: ${{ always() }}
        continue-on-error: true
        run: |
          If (Test-Path "${{ steps.facts.outputs.drive }}\_") { rm -r -fo "${{ steps.facts.outputs.drive }}\_" }
          msys2 -c 'mv -f /etc/pacman.conf.bak /etc/pacman.conf'
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'
